
import { url } from 'inspector'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}
      
      <section>
      <div className={styles.gridContainer}>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>  
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /><p style={{top:"-20px"}}>ADD</p><p style={{top:"22px"}}>+&nbsp;&nbsp;&nbsp;</p><p style={{top:"58px"}}>New</p></div>  
      </div>
      </section>
      <section>
      <div className={styles.containerDiv} >
      <div className={styles.hrtext}>
      <p>NEW MEDIA</p>
      <div className={styles.headerhr}></div>
      <p>MORE &nbsp;{">"}</p>
      </div>
      </div>
      </section>
      <section>
      <div className={styles.gridContainerTwo}>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>  
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>
      <div className={styles.gridItem}><img src={'https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png'} /></div>  
      </div>
      </section>
      <section>
      <div className={styles.containerDiv} >
      <div className={styles.hrtext}>
      <p>NEW USERS</p>
      <div className={styles.headerhr}></div>
      <p>MORE &nbsp;{">"}</p>
      </div>
      </div>
      </section>
      <section className={styles.profileSection} >
      <div className={styles.containerDiv} >  
      <div className={styles.profileBackgroundcover} style={{backgroundImage:`url('https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png')`}} >

      </div>
      <div className={styles.profileTextShow}> 
      <h2>Mosoe<i className={styles.blueTick}></i></h2>
      <div>
        <p>@Joseymosey</p>
        <p>.</p>
        <p>Last Seen 40 mins ago</p>
        <p>.</p>
        <p>#Category  &nbsp;&nbsp;&nbsp; #anotherCaterory  &nbsp;&nbsp;&nbsp;  #category &nbsp;&nbsp;&nbsp; #anotherCaterory</p>
      </div>
      </div>
      <p className={styles.profileBottomText}>Users Providers Description text goes here. Users Provides Users Providers Description text goes here. Users Providers Description text goes here. Users Providers Description text goes here. </p>
      <div className={styles.profilePhotoStyle} style={{backgroundImage:`url('https://imageio.forbes.com/specials-images/imageserve/6069ca73ac8bbc870c18cac0/A-Mallard-duckling-chasing-a-fly-in-a-pond-in-Prague-/960x0.jpg?height=474&width=711&fit=bounds')`}} >

      </div>
      </div>
      </section>
      <section className={styles.profileSection} >
      <div className={styles.containerDiv} >  
      <div className={styles.profileBackgroundcover} style={{backgroundImage:`url('https://upload.wikimedia.org/wikipedia/commons/b/b6/Image_created_with_a_mobile_phone.png')`}} >

      </div>
      <div className={styles.profileTextShow}> 
      <h2>Mosoe<i className={styles.blueTick}></i></h2>
      <div>
        <p>@Joseymosey</p>
        <p>.</p>
        <p>Last Seen 40 mins ago</p>
        <p>.</p>
        <p>#Category  &nbsp;&nbsp;&nbsp; #anotherCaterory  &nbsp;&nbsp;&nbsp;  #category &nbsp;&nbsp;&nbsp; #anotherCaterory</p>
      </div>
      </div>
      <p className={styles.profileBottomText}>Users Providers Description text goes here. Users Provides Users Providers Description text goes here. Users Providers Description text goes here. Users Providers Description text goes here. </p>
      <div className={styles.profilePhotoStyle} style={{backgroundImage:`url('https://imageio.forbes.com/specials-images/imageserve/6069ca73ac8bbc870c18cac0/A-Mallard-duckling-chasing-a-fly-in-a-pond-in-Prague-/960x0.jpg?height=474&width=711&fit=bounds')`}} >

      </div>
      </div>
      </section>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
